language: python
services:
    - postgresql
python:
  - "3.6"
cache: pip
env:
  global:
    - POSTGRES_PASSWORD=""
install:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
  - psql -c 'create database gbs;' -U postgres
  - pipenv run python manage.py makemigrations
  - pipenv run python manage.py migrate
# command to run tests
script:
  - pipenv run python manage.py check
  - pipenv run coverage run --source='gbs/' --omit="gbs/migrations/*,gbs/tests/*" manage.py test gbs
  - coveralls
