language: python
services:
    - postgresql
python:
  - "3.6"
cache: pip
env:
  global:
    - POSTGRES_HOST="127.0.0.1"
    - POSTGRES_PORT="5432"
    - POSTGRES_USER="postgres"
    - POSTGRES_PASSWORD=""
install:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
  - psql -c 'create database gbs;' -U postgres
  - pipenv run python manage.py makemigrations
  - pipenv run python manage.py migrate
# command to run tests
script:
  - pipenv run python manage.py check
  - pipenv run python manage.py test gbs
