# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
os: Visual Studio 2017

# version: {branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  matrix:
    - PYTHON: "C:/Python36-x64"
  SECRET_KEY: "test"
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_NAME: "gbs"
  DB_TABLE: "gbs"
  DB_USER: "postgres"
  DB_PASS: "Password12!"

# enable service required for build/tests
services:
    - postgresql101

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

build_script:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12! 
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb gbs
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # add databases
  - "pip install wheel"
  - "pip install -r requirements.txt"
# to run your custom scripts instead of automatic tests
test_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: "python.exe manage.py showmigrations"
  - cmd: "python.exe manage.py test gbs"

