# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
os: Visual Studio 2015

# version: {branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  matrix:
    - PYTHON: "C:/Python35-x64"
  MYSQL: "C:/Program Files/MySql/MySQL Server 5.7"
  SECRET_KEY: "test"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_NAME: "test"
  DB_TABLE: "test"
  DB_USER: "root"
  DB_PASS: "Password12!"

# enable service required for build/tests
services:
    - mysql

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

build_script:
- ps: $env:MYSQL_PWD="Password12!"
- ps: $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database test;" --user=root'
- ps: iex "& $cmd"
- ps: $cmdb = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "show databases;" --user=root'
- ps: iex "& $cmdb"
# scripts that run after cloning repository
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # add databases
  - "pip install wheel"
  - ps: wget 'https://github.com/PyMySQL/mysqlclient-python/releases/download/1.3.8/mysqlclient-1.3.9-cp35-cp35m-win_amd64.whl' -OutFile "$pwd\mysqlclient-1.3.9-cp35-cp35m-win_amd64.whl"
  - "pip install mysqlclient-1.3.9-cp35-cp35m-win_amd64.whl"
  - cmd: sed -e '/mysqlclient==1.3.9/ s/^#*/#/' -i requirements.txt
  - "pip install -r requirements.txt"
# to run your custom scripts instead of automatic tests
test_script:
  - "SET PATH=%MYSQL%\\bin;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: "python.exe manage.py showmigrations"

