# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
os: Visual Studio 2017

# version: {branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# enable service required for build/tests
services:
    - postgresql101

# environment variables
environment:
  DATABASE_URL: "postgres://postgres:Password12!@127.0.0.1:5432/gbs"
  matrix:
    - PYTHON: "C:/Python36-x64"

init:
  - "SET PGUSER=postgres"
  - "SET PGPASSWORD=Password12!"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

cache:
  # Cache Pip install
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'

build_script:
  - "SET PATH=C:\\Program Files\\PostgreSQL\\10\\bin\\;%PATH%"
  - createdb gbs
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # add databases
  - cmd: "pip install -r requirements.txt"
  - cmd: "mkdir staticfiles"
  - cmd: "python manage.py collectstatic"
  - cmd: "python manage.py showmigrations"
  - cmd: "python manage.py makemigrations"
  - cmd: "python manage.py migrate"
# to run your custom scripts instead of automatic tests
test_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: "python manage.py test gbs"

