version: '2'
volumes:
  pg_data: {}
  pg_backup: {}
services:
  nginx:
    restart: always
    build: ./docker/nginx
    container_name: gbs-web
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=gbs.ballyda.com
      - LETSENCRYPT_HOST=gbs.ballyda.com
    expose:
      - "80"
      - "443"
    volumes:
       - "/etc/letsencrypt/:/etc/letsencrypt/:ro"
       - "/var/www/html:/var/www/html:ro"
       - "/etc/ssl/:/etc/ssl/:ro"
    volumes_from:
      - "django"
    links:
      - "django:django"
    networks:
      - areio_default
  django:
    restart: always
    container_name: gbs-dj
    build: .
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/static"
    env_file: .env
    links:
      - psql:psql
    expose:
      - "8000"
    networks:
      - areio_default
  psql:
    restart: always
    container_name: gbs-psql
    image: postgres:9.5
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backup:/backups
    env_file: .env
    expose: 
      - "5432"
    networks:
      - areio_default
networks:
  areio_default:
    external: true
  # pgadmin:
  #   restart: always
  #   image: fenglc/pgadmin4
  #   links:
  #     - psql:psql
  #   ports:
  #     - "5050:5050"

