version: '2'
volumes:
  postgres_data_local: {}
  postgres_backup_local: {}
services:
  nginx:
    restart: always
    build: ./docker/nginx
    container_name: web
    volumes_from:
      - "django"
      - "certbot"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "django:django"
  django:
    restart: always
    container_name: django
    build: .
    command: bash -c './manage.py makemigrations && ./manage.py migrate && ./manage.py loaddata db && gunicorn tine.wsgi:application -w 2 -b :8000 --log-level DEBUG'
    volumes:
      - /usr/src/app/static
    env_file: .env
    links:
      - psql:psql
    expose:
      - "8000"
  psql:
    restart: always
    container_name: psql
    image: postgres:9.5
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file: .env
    expose: 
      - "5432"
  certbot:
    restart: always
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/html/ -d www.groganburners.com -d groganburners.com -d www.groganburners.ie -d groganburners.ie
    volumes:
      - "/etc/letsencrypt:ro"
      - "/var/lib/letsencrypt:ro"
      - "/var/www/html:ro"
      - "/etc/ssl/:ro"
  # pgadmin:
  #   restart: always
  #   image: fenglc/pgadmin4
  #   links:
  #     - psql:psql
  #   ports:
  #     - "5050:5050"

