version: '2'
volumes:
  postgres_data_local: {}
  postgres_backup_local: {}
services:
  nginx:
    restart: always
    build: ./docker/nginx
    container_name: web
    volumes_from:
      - "django"
    ports:
      - "8000:80"
    links:
      - "django:django"
  django:
    restart: always
    container_name: django
    build: .
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && /usr/local/bin/gunicorn tine.wsgi:application -w 2 -b :8000 --log-level DEBUG'
    volumes:
      - /usr/src/app/static
    env_file: .env
    links:
      - psql:psql
    expose:
      - "8000"
  psql:
    restart: always
    container_name: psql
    image: postgres:9.5
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file: .env
    expose: 
      - "5432"
  pgadmin:
    restart: always
    image: fenglc/pgadmin4
    links:
      - psql:psql
    ports:
      - "5050:5050"

