version: '2'
services:
  django:
    restart: always
    container_name: django
    build: .
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && /usr/local/bin/gunicorn tine.wsgi:application -w 2 -b :8000 --log-level DEBUG'
    volumes:
      - /usr/src/app/static
    env_file: .env
    links:
      - psql:psql
    ports:
      - "8000:8000"
  psql:
    restart: always
    container_name: psql
    image: postgres:9.5
    volumes_from:
      - data
    env_file: .env
    expose: 
      - "5432"
  data:
    restart: always
    container_name: data
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql
    command: "true"
  pgadmin:
    restart: always
    image: fenglc/pgadmin4
    links:
      - psql:psql
    ports:
      - "5050:5050"

