version: '2'
volumes:
  pg_data: {}
  pg_backup: {}
services:
  django:
    restart: always
    container_name: tine
    build: .
    volumes:
      - ".:/app"
    environment:
      DATABASE_URL: postgres://postgres:postgres@psql:5432/gbs
      PORT: 5000
      SECRET_KEY: testmeimasecretkey
    links:
      - psql:psql
    expose:
      - "5000"
  psql:
    restart: always
    container_name: psql
    image: postgres:10.4
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backup:/backups
    environment:
      POSTGRES_DB: gbs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
  # pgadmin:
  #   restart: always
  #   image: fenglc/pgadmin4
  #   links:
  #     - psql:psql
  #   ports:
  #     - "5050:5050"

