version: '3.4'
volumes:
  pg_data: {}
  pg_backup: {}
services:
  django:
    restart: always
    container_name: tine
    build: .
    depends_on:
      - psql
    volumes:
      - ".:/app"
    environment:
      DATABASE_URL: postgres://postgres:postgres@psql:5432/gbs
      PORT: 5000
      SECRET_KEY: testmeimasecretkey
    links:
      - psql:psql
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
  psql:
    restart: always
    container_name: psql
    image: postgres:10.4
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backup:/backups
    environment:
      POSTGRES_DB: gbs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
  # pgadmin:
  #   restart: always
  #   image: fenglc/pgadmin4
  #   links:
  #     - psql:psql
  #   ports:
  #     - "5050:5050"

