version: 2
jobs:
  build:
    working_directory: ~/tine
    docker:
      - image: circleci/python:3.6
        enviroment:
          SECRET_KEY: test
          DJANGO_DEBUG: true
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: gbs
          DB_USER: ubuntu
          DB_PASS: 12345
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: gbs
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: 12345
    steps:
      - checkout
      # - restore_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Pipenv
          command: pip install pipenv
      - run:
          name: Install Pipenv Dependencies
          command: pipenv install
      # - save_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #     paths:
      #       - "venv"
      - run:
          name: Django Make Migrations
          command: pipenv run python manage.py makemigrations
      - run:
          name: Django Migrate
          command: pipenv run python manage.py migrate
      - run:
          name: Django Run Tests
          command: pipenv run python manage.py test
      # - store_artifacts:
      #     path: test-reports/
      #     destination: tr1

