version: 2
jobs:
  build:
    working_directory: ~/tine
    enviroment:
      SECRET_KEY: test
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: gbs
      DB_USER: ubuntu
      DB_PASS: 12345
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: '12345'
          POSTGRES_DB: gbs
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            env
            python manage.py makemigrations
            python manage.py migrate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1

