version: 2
jobs:
  build:
    working_directory: ~/tine
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: gbs
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: add user installs to PATH
          command: |
              echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
              echo 'export WORKON_HOME=$HOME/.venvs' >> $BASH_ENV
      - run:
          name: Install Pipenv
          command: |
            pip install --user pipenv
            pipenv install -d
            env
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.venvs"
            - "~/.local"
      - run:
          name: Django Make Migrations
          command: pipenv run python manage.py makemigrations
      - run:
          name: Django Migrate
          command: pipenv run python manage.py migrate
      - run:
          name: Django Run Tests
          command: pipenv run coverage run --source='gbs/' --omit="gbs/migrations/*,gbs/tests/*" manage.py test gbs
      - run:
          name: Generate Code Coverage Report
          command: pipenv run coverage html
      - store_artifacts:
          path: htmlcov/
          destination: tr1

