version: 2
jobs:
  build:
    working_directory: ~/tine
    enviroment:
      WORKON_HOME: "~/.venvs"
      SECRET_KEY: test
      DJANGO_DEBUG: true
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: gbs
      DB_USER: ubuntu
      DB_PASS: 12345
    docker:
      - image: circleci/python:3.6
        enviroment:
          WORKON_HOME: "~/.venvs"
          SECRET_KEY: test
          DJANGO_DEBUG: true
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: gbs
          DB_USER: ubuntu
          DB_PASS: 12345
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: gbs
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: 12345
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: add user installs to PATH
          command: |
              echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Pipenv
          command: |
            pip install --user pipenv
            pipenv install -d
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.venvs"
            - "~/.local"
      - run:
          name: Django Make Migrations
          command: pipenv run python manage.py makemigrations
      - run:
          name: Django Migrate
          command: pipenv run python manage.py migrate
      - run:
          name: Django Run Tests
          command: pipenv run python manage.py test
      # - store_artifacts:
      #     path: test-reports/
      #     destination: tr1

