release: python manage.py makemigrations && python manage.py migrate --noinput&& python manage.py collectstatic --no-input
web: gunicorn tine.wsgi:application -w 2 -b :5000 --reload --log-level DEBUG
