- hosts: all
  vars:
    app_name: "tine"
    ssh_public_key_file: "~/.ssh/id_git.pub"
    dokku_public_key_file: "{{ansible_env.HOME}}/dokku_key.pub"
    dokku_version: 0.20.4
    install_dokku: "/tmp/install-dokku-{{dokku_version}}.sh"
  tasks:
    - name: download dokku script
      get_url:
        url: https://raw.githubusercontent.com/dokku/dokku/v{{dokku_version}}/bootstrap.sh
        dest: "{{install_dokku}}"
    - name: change permissions on dokku script 
      file:
        path: "{{install_dokku}}"
        mode: u+x
    - name: Check Dokku dokku_version
      command: dokku version
      register: dokku_version_result
      changed_when: false
      failed_when: dokku_version_result.rc != 0 and dokku_version_result.rc != 2
      become: true
    - name: Install dokku_version
      command: "{{install_dokku}}"
      register: install_dokku_result
      changed_when: install_dokku_result is succeeded
      become: true 
      when: dokku_version_result.rc == 2 or dokku_version not in dokku_version_result.stdout
      environment:
        DOKKU_TAG: v{{dokku_version}}
        DOKKU_WEB_CONFIG: "false"
        DOKKU_SKIP_KEY_FILE: "true"
        DOKKU_VHOST_ENABLE: "true"
    - name: Remove nginx default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: true
    - name: Copy SSH Key to host
      copy:
        src: "{{ssh_public_key_file}}"
        dest: "{{dokku_public_key_file}}"
    - name: Check SSH Key signature
      command: ssh-keygen -l -f {{dokku_public_key_file}}
      register: ssh_keygen_result
      changed_when: false
    - name: Check for SSH Keys in Dokku
      command: dokku ssh-keys:list
      register: dokku_keys_result
      changed_when: false
      failed_when: dokku_keys_result.rc != 0 and "No public keys found" not in dokku_keys_result.stderr
      become: true 
    - name: Add SSH pubkey to Dokku
      command: bash -c 'dokku ssh-keys:add admin {{dokku_public_key_file | quote}} < /dev/null'
      register: dokku_add_key_result
      changed_when: dokku_add_key_result is succeeded
      become: true
      when: "'%s NAME=\"admin\"' % ssh_keygen_result.stdout.split(' ')[1] not in dokku_keys_result.stdout"
    - name: List Dokku Apps
      command: dokku apps:list
      register: dokku_apps_list_result
      become: true
      changed_when: false
    - name: Create our app if it doesnt exist
      command: dokku apps:create {{app_name}}
      register: dokku_apps_create_result
      become: true
      when: app_name not in dokku_apps_list_result.stdout
      changed_when: dokku_apps_create_result is succeeded
    - name: Check Dokku Plugins
      command: dokku plugin:list
      register: dokku_plugin_result
      changed_when: false
    - name: Install Postgres Dokku Plugin
      command: dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres
      register: dokku_plugin_install_postgres_result
      become: true
      when: "'postgres' not in dokku_plugin_result.stdout"
      changed_when: dokku_plugin_install_postgres_result is succeeded
    - name: List Postgres Databases
      command: dokku postgres:list
      become: true
      register: dokku_postgres_list_result
      changed_when: false
    - name: Create Postgres Database
      command: dokku postgres:create {{app_name}}
      register: dokku_postgres_create_result
      become: true
      when: app_name not in dokku_postgres_list_result.stdout
      changed_when: dokku_postgres_create_result is succeeded
    - name: Check Dokku Postgres App Links
      command: dokku postgres:info {{app_name}} --links
      become: true
      register: dokku_postgres_info_result
      changed_when: false
    - name: Link Dokku Postgres to our app
      command: dokku postgres:link {{app_name}} {{app_name}}
      register: dokku_postgres_link_result
      become: true
      when: app_name not in dokku_postgres_info_result.stdout
      changed_when: dokku_postgres_link_result is succeeded