# Generated by Django 3.0.2 on 2020-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to='images/hero'),
        ),
    ]
