# Generated by Django 6.1.1 on 2026-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs', '0002_auto_20200114_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='season',
            field=models.CharField(blank=True, choices=[('', 'All year'), ('spring', 'Spring (March–May)'), ('summer', 'Summer (June–August)'), ('autumn', 'Autumn (September–November)'), ('winter', 'Winter (December–February)')], default='', help_text='Seasonal banners take priority over All year banners. Only active banners appear. If several match, the oldest is shown.', max_length=6),
        ),
    ]
